language: python
python:
  - "2.7"
sudo: required
services:
  - docker
before_install:
  - python setup.py install
  - docker version
  - docker pull tutum/hello-world
  - docker run -d -p 80:80 tutum/hello-world
  - docker run -d -p 81:80 tutum/hello-world
  - docker run -d -p 50001:80 tutum/hello-world
  - docker ps -a
# install dependencies
install: "sudo pip install -r requirements.txt"
# test unitaires
script:
  - cat ports/tests/unit/testport.py
  - python --version
  - python ports/tests/unit/testport.py
virtualenv:
    system_site_packages: true
