language: python
python:
  - "2.7"
addons:
    code_climate:
        repo_token: 36e4d37a992481f1492376663ae6432ff8740ef5119c68fcc13e3104019ff070
sudo: required
services:
  - docker
before_install:
  - python setup.py install
  - pip install codeclimate-test-reporter
  - docker version
  - docker pull tutum/hello-world
  - docker run -d -p 80:80 tutum/hello-world
  - docker run -d -p 81:80 tutum/hello-world
  - docker run -d -p 50001:80 tutum/hello-world
  - docker ps -a
after_success:
  - coverage run logs/logs.py
  - codeclimate-test-reporter
# install dependencies
install: "sudo pip install -r requirements.txt"
# test unitaires
script:
  - python --version
  - python ports/tests/unit/testport.py
virtualenv:
    system_site_packages: true
